### ISSUE TITLE
Publishing on hackage?

### ISSUE THREAD

**Issue by ghuntley** [chessai/hedgehog-classes#2]
Howdy @chessai

Wondering what your intentions are roadmap wise before you'll publish on Hackage? 

pps - what you have right now suffices for a 0.0.1 release if you are happy with the shape of the public API surface.

**Comment by chessai** [comment]
For a 0.1.0.0 release i need to complete the test suite and establish a GHC compatibility window, eg GHC >= 7.10.3 && < 8.8

**Comment by chessai** [comment]
The public API is certainly what i consider to be stable/final.

The only thing lacking (not necessary for an initial release) is the ability to test higher-kinded properties with constrained element types. Eg for all higher-kinded laws we have:

```haskell
hLaws :: forall f.
  ( forall x. Eq x => Eq (f x)
  , forall x. Show x => Show (f x)
  ) => (forall x. Gen x -> Gen (f x))
     -> Laws
```

But, `x` cannot be constrained here, meaning we cannot do something like the following:

```haskell
genSet :: Ord a => Gen a -> Gen (Set a)
genSet gen = do
  xs <- Gen.list (Range.linear 0 20) gen
  pure (Set.fromList xs)

setLaws :: [Laws]
setLaws = [foldableLaws genSet]
```
We get an error about the constraint. We also cannot monomorphise the type variable 'a', because that would break the universal quantifier (since it's not a use site thereof).

So i am considering the introduction of roughly the following into the API:

```haskell
foldableLaws :: forall f a.
  ( Eq a, Show a
  , Eq (f a), Show (f a)
  ) => Gen (f a) -> Laws
```

while somehow not exposing implementation details.

**Comment by chessai** [comment]
The test suite is currently incredibly inperformant, so a release is blocked on that. I need to check and see what the problem is - hopefully just something stupid i've done here, like generating something really big when i dont need to. my current suspicions are in applicativeLaws/traversableLaws, since those use some weird applicative transformation hack.

**Comment by chessai** [comment]
docs are building.

**Comment by chessai** [comment]
https://hackage.haskell.org/package/hedgehog-classes

**Comment by ghuntley** [comment]
Cheers
